### ISSUE TITLE
Instantiating class `new BV` on PHP 7.0.8 under Apache kills httpd

### ISSUE THREAD

**Issue by indextwo** [bazaarvoice/seo_sdk_php#2]
I was originally developing a site with BV SEO integration on Apache 2.4.17 running PHP 5.5.24 (on a Win7 environment with XAMPP). This appeared to work fine. However, the site required some platform upgrades, so I upgraded the development server to Apache 2.4.18 & PHP 7.0.8, and now instantiating the `new BV()` class crashes Apache immediately, every time.
## Update:

This can be traced to the `BVUtility::execTimer()` function called on [line 427 of bvseoskd.php](https://github.com/bazaarvoice/seo_sdk_php/blob/master/bvseosdk.php#L427) and looks to be related to [this open PHP bug](https://bugs.php.net/bug.php?id=72832). It _may_ be related to multithreading, but this isn't confirmed.

Commenting out line 427 ensures that it doesn't crash out Apache, but the issue should be addressed.

**Comment by msmolev** [comment]
Hi @indextwo ,

Does the problem happen with version 7.0.10 as well (thread-safe version)?

Thanks

**Comment by indextwo** [comment]
No idea - I only just installed the latest XAMPP package with 7.0.8 on Saturday evening. I can try with a thread-safe install of 7.0.10 but it will take some time to get set up.

**Comment by msmolev** [comment]
If it's possible, could you please try the thread-safe version? I don't have a Windows 7 system handy to be able to replicate the issue and it would help a lot.

Thanks

**Comment by indextwo** [comment]
Unfortunately, upgrading the PHP version doesn't seem to have made any difference; on PHP 7.0.10 x86 thread-safe version (http://windows.php.net/download/#php-7.0-ts-VC14-x86) the same error occurs under the same circumstances.

**Comment by jenriquez77** [comment]
Released a fix for this issue in version 3.2.1
