### ISSUE TITLE
PHP8.2 compatibility: Deprecated function: Creation of dynamic property

### ISSUE THREAD

**Issue by PavelSPN** [bazaarvoice/seo_sdk_php#7]
On PHP8.2 the next deprecations appeared:

Deprecated function: Creation of dynamic property BV::$config is deprecated in BV (line 80, 143, 144, 145, 146, 147, 158 of /libraries/bazaarvoice-seo-sdk/bvseosdk.php).

Deprecated function: Creation of dynamic property Reviews::$start_time is deprecated in Base (line 409, 318, 736, 214, 217, 214, of /libraries/bazaarvoice-seo-sdk/bvseosdk.php).

**Comment by PavelSPN** [comment]
created PR https://github.com/bazaarvoice/seo_sdk_php/pull/8

**Comment by alanlapthorn-bv** [comment]
Archiving repo - closing issues
